### ISSUE TITLE
React Fragment Sugar

### ISSUE THREAD

**Issue by sean1188** [thewhiteline/thewhiteline#8]
## Description
For readability's sake lets try to avoid using this sugar. It's causing ugly syntax highlighting which doesn't make JSX more readable 🤨. "Note that the `<></>` syntax does not accept attributes, including keys."

## Possible Fix

I suggest for consistency, we stick to using the original `<Fragment></Fragment>` syntax.

_ps: sorry for meme-ing during pull #7 's review_

**Comment by ravernkoh** [comment]
Resolved in #9.
